[package]
name = "hashbench"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32.5"
blake2 = "0.10.6"
blake3 = "1.8.2"
criterion = "0.5.1"
rand = "0.9.1"
rand_chacha = "0.9.0"
sha2 = "0.10.9"
sha3 = "0.10.8"

[[bench]]
name = "hash"
harness = false
